services:
  #* 1. Minio
  minio:
    container_name: minio_server
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    restart: unless-stopped
    command: server /data --address ":9000" --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_BROWSER: true
    env_file:
      - .env
    volumes:
      - food_minio_storage:/data
    ports:
      - "9100:9000" # S3 API
      - "9001:9001" # MinIO Console

volumes:
  food_minio_storage:
    driver: local
